apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.14.0
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=in2-dome-marketplace-test.org
            - --provider=webhook
            - --webhook-provider-url=http://localhost:8888
      sidecars:
        - name: ionos-webhook
          image: ghcr.io/ionos-cloud/external-dns-ionos-webhook:v0.6.0
          ports:
            - containerPort: 8888
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - name: LOG_LEVEL
              value: debug
            - name: IONOS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ionos-credentials
                  key: api-key
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: IONOS_DEBUG
              value: "true"
