apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-tls
  namespace: cert-manager
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-ionos
    kind: ClusterIssuer
  dnsNames:
  - in2-dome-marketplace-test.org
 