apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: in2
spec:
  ports:
    - port: 443
      targetPort: 10250
  selector:
    app: cert-manager
    component: webhook
  type: ClusterIP
