apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ionos
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: domesupport@in2.es
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        webhook:
          groupName: acme.fabmade.de
          solverName: ionos
          config:
            apiKeySecretRef:
              name: ionos-credentials
              key: api-key
            endpoint: https://dns.de-fra.ionos.com
