apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ionos
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yani.aici@in2.es #TODO: What email address should we use?
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        webhook:
          solverName: ionos
          groupName: acme.fabmade.de
          config:
            apiTokenSecretRef:
              name: ionos-credentials
              key: api-key
            endpoint: https://dns.de-fra.ionos.com
 