apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ionos
spec:
  acme:
    email: {{ .Values.dome.maintainer.email }}
    preferredChain: ""
    privateKeySecretRef:
      name: lets-encrypt-ionos-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "{{ .Values.dome.dnsName }}"
      http01:
        ingress:
          ingressClassName: nginx