apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ionos
spec:
  acme:
    email: yani.aici@in2.es
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "in2-dome-marketplace-test.org" 
      http01:
        ingress:
          ingressClassName: nginx