apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ionos
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@in2.es #TODO: What email address should we use?
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        webhook:
          groupName: example.com  # TODO: We need to change this to our domain
          solverName: ionos
          config:
            apiTokenSecretRef:
              name: ionos-credentials
              key: api-key
            endpoint: example.com
