apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    purpose: ssi-hub
spec:
  project: default
  source:
    repoURL: https://github.com/in2workspace/in2-dome-gitops
    targetRevision: HEAD
    path: ionos/ssi-hub/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: ssi-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true