business-api-ecosystem:
  bizEcosystemApis:
    # should set the path to the new apis.
    fullnameOverride: tmforum-api-proxy
    enabled: false
    tmForum:
      catalog:
        host: tm-forum-api-product-catalog.marketplace.svc.cluster.local
        port: 8080
        path:
      inventory:
        host: tm-forum-api-product-inventory.marketplace.svc.cluster.local
        port: 8080
        path:
      ordering:
        host: tm-forum-api-product-ordering-management.marketplace.svc.cluster.local
        port: 8080
        path:
      billing:
        host: tm-forum-api-account.marketplace.svc.cluster.local
        port: 8080
        path:
      usage:
        host: tm-forum-api-usage-management.marketplace.svc.cluster.local
        port: 8080
        path:
      party:
        host: tm-forum-api-party-catalog.marketplace.svc.cluster.local
        port: 8080
        path:
      customer:
        host: tm-forum-api-customer-management.marketplace.svc.cluster.local
        port: 8080
        path:
      resources:
        host: tm-forum-api-resource-catalog.marketplace.svc.cluster.local
        port: 8080
        path:
      services:
        host: tm-forum-api-service-catalog.marketplace.svc.cluster.local
        port: 8080
        path:
      resourceInventory:
        host: tm-forum-api-resource-inventory.marketplace.svc.cluster.local
        port: 8080
        path:

  bizEcosystemRss:
    enabled: false

  siop:
    enabled: true
    clientId: did:key:zDnaepbqHQzLvDFUMFZ4u3aENpuGU77y43DqtncHfH4Yh1xyY
    verifier:
      host: https://verifier.dome-marketplace-lcl.org
      qrCodePath: /oidc/authorize
      tokenPath: /oidc/token
      jwksPath: /oidc/jwks
    allowedRoles:
      - seller
      - customer
      - admin
    # Configuration for the Credential Config Service initiation
    ccs:
      endpoint: "http://credentials-config-service.marketplace.svc.cluster.local:8080"
      defaultOidcScope: "defaultScope"
      # -- Credential configurations for particular scopes
      oidcScopes:
        didRead:
          - type: "VerifiableCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
          - type: "LegalPersonCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
          - type: "LEARCredentialEmployee"
            trustedParticipantsLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
        defaultScope:
          - type: "VerifiableCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
          - type: "LegalPersonCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
          - type: "LEARCredentialEmployee"
            trustedParticipantsLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
            ]

  externalUrl: https://marketplace-dev.dome-2.ssihub.org
  bizEcosystemChargingBackend:

    maxUploadSize: "5242880"

    serviceAccount:
      create: true

    deployment:
      image:
        repository: fiware/biz-ecosystem-charging-backend
        tag: 9.1.2
        pullPolicy: Always

    plugins:
      enabled: true
      annotations:
        helm.sh/resource-policy: "keep"

    media:
      enabled: true

    port: 8006

    loglevel: debug

    payment:
      method: None

    existingSecret: bae-secret
    db:
      host: mongodb
      database: charging_db
      user: charging

    backup:
      enabled: false

    initContainers: false
    propagateToken: true
    basePath: /opt/business-ecosystem-charging-backend
    token:
      enabled: false

  oauth:
    provider: "vc"

  bizEcosystemLogicProxy:
    serviceAccount:
      create: true

    existingSecret: bae-secret

    statefulset:
      image:
        repository: fiware/biz-ecosystem-logic-proxy
        tag: "9.11.4"
        pullPolicy: Always

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
      tls:
        -  hosts:
             - marketplace-dev.dome-2.ssihub.org
           secretName: bae-tls-secret
      hosts:
        - host: marketplace-dev.dome-2.ssihub.org
          paths:
            - "/"

    port: 8004
    nodeEnvironment: production

    db:
      host: mongodb
      database: belp_db
      user: belp
    basePath: /opt/business-ecosystem-logic-proxy

    externalIdp:
      enabled: true
    initContainers: false
    propagateToken: true
    additionalEnvVars:
      - name: BAE_LP_SIOP_IS_REDIRECTION
        value: "true"
      - name: BAE_LP_CHAT_URL
        value: https://eng-gpt.dome-marketplace-sbx.org/predict
      - name: BAE_LP_KNOWLEDGE_BASE_URL
        value: https://knowledgebase.dome-marketplace-sbx.org/
      - name: BAE_LP_TICKETING_URL
        value: https://ticketing.dome-marketplace-sbx.org/
      - name: BAE_LP_SIOP_OPERATORS
        value: did:elsi:VATES-B87798617
      - name: BAE_LP_SEARCH_URL
        value: http://dome-search-svc.search-engine.svc.cluster.local:8080
      - name: BAE_LP_MATOMO_ID
        value: "2"
      - name: BAE_LP_MATOMO_URL
        value: https://dome-webstats.eurodyn.com/
      - name: BAE_LP_DOME_TRUST
        value: https://dome-certification.dome-marketplace-sbx.org
      - name: BAE_LP_PURCHASE_ENABLED
        value: "true"
      - name: BAE_LP_DOME_ABOUT
        value: https://dome-project.eu/about/
      - name: BAE_LP_SIOP_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: bae-secret
            key: privateKey