apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dome-wallet
spec:
  acme:
    email: oriol.canades@in2.es
    privateKeySecretRef:
      name: letsencrypt-in2-dome-dev-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
