---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scorpio-secret
  namespace: marketplace
spec:
  encryptedData:
    postgres-password: AgDE6keeUOYi9b20LVH90JMbjYFqCpU8+XcRhVDvCwn2QTsx8hYJBkpEpjXtHXLfjYeie/E8aAO9E/lQz3oLvfIjknGmVVXtJrzO2hssqcNrF0ZPsbhDLJT0WsFpUNCVvmcbN5aZ4j5GOJQtNyhNvWhdY/aJsQCKCt4TXcQ5cQpm5wBMhL2Cyf4hrZbMCRzJZFYbrFhAw8RrYrV249FvdJ/fjPhn/hzrU/B2kWscHZO19rxmL/7R5ZrRFdbGVIvf3wRaoR3VgMaatlrqIakxCssW/6Vc6Mpf/CrJJLgoAquzWIEDdmzGDaFFrKT2hh/y2ygvfIxQlcImO1bj2eP3wPZi8S0K9DhLPMUXoqO9epmST7Ni2LabLtIrhEJmomMNxcYC3Jf6+9JpL3CiS2wYdIal+Hdif94Tfcy/6DfI+Uc0FuDv2kPsRXf+w8pQay3QkPmQMFsBPylOzahZw4HO5AqEd1wUfHuCjnka8O3LKxIJnJDqVTyv9PyUhx3Xn/sC1w29vFiZcnZhCw+JyonAqbSifqyjhV9imvobBsI6kgdfob2+6gou0MTp4p/VJobsgB+UxfACs9qG+rRVbd7i79UXBCkZ7iBR+TOTLbMwkE4XR0L4uyx6zy412uQzvriTFc3vg0J01BlNt8Oob/0oQiXsG6AMTqlWyQzTcT5Qs5k0zWL2CGndPpbXW3uKPLTDHONtfygry+gO9gmyGTc=
  template:
    metadata:
      creationTimestamp: null
      name: scorpio-secret
      namespace: marketplace
