---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scorpio-secret
  namespace: marketplace
spec:
  encryptedData:
    postgres-password: AgC2rf+TrRQ/Zi0B9nZcP0rWk3diK6bw0PXpRb9XOMpxc1uimVMlAheSjNe/Xw2bHOjxpumrnJvfuTAxYExmxnl6s0w/qwVxkqyId3k9QR3nhS7la2fJE31/wV+/PRlfuy+V0nlYZ827eXoxkE41Mu9ZbxAFB4usEKx5CVzV3nR6bjwOx6RkHenpSlpPeIBBWMqjLxZvoD1LXGlh8w6csF4g4TLOX2SiDufNiV51uC6q+uBpveDRZIUjHdKntFgQR4nz6jCGlRvO1zYqWBWIfPCFzDgwcH820GOvwyb2mcla1uPVb0opYETGMbKrHVM9d8zPUUcsKz4FITEantoQrHB5B5JYMZKwu7qE/lzRGuAqjI4t9coRa5z98HS3IBTQTTUQQn4Sc6aPKyW0hxfZWZ6JPuTEKUvXM7sKajXDv3TB7mheH9KucDz04zG36kj8T8iHRecFk7PimNC1sq0tdxHyVqaC2w8w4WYMdD8sE3ydOKsE9+mJSnmGgfWci9v8nsJ9VcDDUTVgNAg8wsJbw+EEWr8wRE6ycTwq37du5BddUV9xjnHn5rdd+7pi6IFT6JPqdq/XVR+sxGcUvAQAg7yN33u1PxAvsshptRtHCBgrKXa9/XPL+hdre8mMEJPVCWQfJiGk1IPZtzKnn8TWg7piadYBCEt3hN1NL51m6h5gMLOf2sMgamubWNP71uF/kE3Ywe/MLNxZv7kqV1M=
  template:
    metadata:
      creationTimestamp: null
      name: scorpio-secret
      namespace: marketplace
