---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-env-secret
  namespace: marketplace
spec:
  encryptedData:
    MONGO_BAE_BELP_PW: AgBK7Azn00IUxn84w3SKU1ft2pHQrDAMkJw64W5ZxJSQlENNsOVLjW0hWgkd6QTvJeewo6UQsvJBl5ZzZervI29ULDCkXkd2ytEL02nVnQt2asXpi7HnsKCqPONLYSkQXgEbg4b3S4qgK+JHNl3yCG6RuKj8Q0m8/jOuW7xfq7qqtorTcPSDCXF/QPBtWqT3W9k1/zY2VUSdVCswQr+joZGZS/1w0DnYKTpB7X/gUW7CllgAdLlWfd2OyCzK9sFaPk/tNzwTTu74NOQ901dZ+JixOvX/yaPm0K/BxsDIvfTYcwD9dYWTXmi1LrINr/WA37y+Yg02X7FeZXfAt7NjCPjbycbrIgM28qf3/4roOYu0hynPCQ2U4ZRCjSxU/r8Nw8xv2BH9GszzLhPyMDXbGk4ogNTkwd8eu45xC5NhxU5TCPl2xJR93K/Vq2UTef6cpbYPczkZuJYRyZfa3acY+myR2EV8xIBii2U2Sz4aaR1Q39oAPrpWaBJHpaUC/10n7c5r1aZQjsnVhkpdBW/syzO0x6ByE9FSD6rtEljqSNSOrtHLag5G0UG0UC9yApV2hgZ3uwgEnn3d65Zwu96XAZokDndbCoowgV8Tg+vccj+w1wyWXE07F1VY+mG6HYt2+8MyirFSkuCXYixcpahLcxMe97MLt5crFzzKVMyauXJYXw5kjA8goSYlSAmHOWec7gTkfWTlUx8eUBPfYCQ=
    MONGO_BAE_CHARGING_PW: AgCKUNVQ9w2vjbEipXXjXwBdMZilnG2At+s1ImZekGd/pNUEHxDdvxjTCBkjphjihuzoVMjyvQJ/+GGW8EVKiaZhftFCn0xIIh8sXmUDI/vdlv1dsKS0L1MFMNMmOeIUUFgaBnKMeirLmruaQvFGuoWPaptOtiJtAN+/hrJ/q9NS5WGxelfiXUqHyxJ7K33kF5HFbYXF7TTLaxv5vOdpSOQ1DKiq0Cov9cdbs+E0qbG2+e65q5SHsusQAfwxvzoQJTAs5a8IncVbljiLrixMFl7nkAc6PMSa0fqbZUNbiSPIOwg/ImPLPGc5vfcM7EqdDmhQNn53M3Nz/Oa3FTAcdKyo6Rj5h3mOWw5PaBI5hkiQrMB2UOynTB1n3ONLOUcxHk66+QoA8uMyi3HYcU3BaTruWCqiqTgCCEaR9R+nIbk1wyav+O73pBrPvKZS++UjgGqWflCDnRgE4ycMeGo1P9EALqbZWnQMEyP+sKZb534k7a5ku1u5oR4dj0kA7lOZjwC+WnJlvuOpIZnwPCldNaR3vKg8S67H6q1p/n0lAVMRBzzygKgXig3N4QtvDzigQ5vmw08v71ty0szzGzpRIZ3/WsJRwY8QCpnpAEBPRANWyVaomzFf18UGVKJjGoBnMsHSf6cPLBPX8OFVZzlSTZwxsrm9dnyoHDj6gkWPRCP1w1+tu+jffzaDZs+Unx4rrXZzxlBfO6qL504ng3U=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-env-secret
      namespace: marketplace
