---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: marketplace
spec:
  encryptedData:
    mongodb-root-password: AgC6Dq7u93qhQoOmSivdir3iL3WYK35Lok15ow9Gf7YrhA1FbPrlLLWjKqW8Pxnv6A/Mm03S9tXHYcimLhgwoBGCBaodEXbowTw8ysRx2VMv6fBl2wTfe/D7QLD4QZCbKay0h8p2ERwTvlm8bbl24HD+wuJkAKnyu9ox3BSvqMGVGWo32+PBS2L2IwmCybdlTc49xqrbvU6tnOXMkndFEhyPon65OkvkF0aia1OUWhPUAPZUo1q1He3Yl9QhFh9wYEMVZ6dFHZqJil+D7xPgLnhYZApd9c0v0Q7mlVyxTsTKFH0Ia7HMaorhdoX1IIlUbm+5zgIgl1zEzt3/1osIps8DufIfGwXP8JrLOhX5UFjDVYetcYqXp7AV0BQKI7DRH47aEUZH9CqcK0bGAaw9NG6VhluQHds7zPqXXveu+6PfaRQBMPP77ZmbOycUzpRD/iv93G2CCUEwqx8v7+ZfoFiWOUE91HOC9U7wOT7WdklT/ov/YdcuRU9mfQ6+W8oLHYgiE/HNCRiGTeuLUJNPdJRFc3biDGxyTPk3aQTqmtQ9wNnU5VhJUUJWuQ+MqB7L+2ohXOc1I+MzZrMRSd3WsZR6axVJy8yCDn0m5ZJtW86BdtTMWP1U8SsBFVFSDY+hbHPJ1UQOps4CuZOu6wp09/HOrwh9lJUqLzPROtkXpC8QrKFrkcTK+wLFQdCIoCe1BCi/lRu3hePfzAgfIXM=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: marketplace
