global:
  tenantName: "in2"
  environment: "dev"
  # Se usa para construir el ingress.hosts.host: wallet.{{ tenantName }}.{{ externalDomain }}
  externalDomain: "wallet-dev.in2.ssihub.org"
  ingress:
    enabled: true
    className: "nginx"
    sslRedirect: false
    backendProtocol: "HTTP"
    enableTLS: false
    clusterIssuer: "letsencrypt-in2-test-issuer"

wallet:
  enabled: true
  # Wallet Backend subchart configuration
  wallet-backend:
    # -- should be enabled?
    enabled: true
    # Image configuration
    image:
      pullPolicy: Always
      tag: v1.4.1
    # Application specific configuration
    app:
      logLevel: DEBUG
      db:
        existingSecret:
          # -- should an existing secret be used?
          enabled: true
          # -- name of the secret
          name: tenant-in2-wallet-sealed-secret
          # -- key to retrieve the secret from
          key: postgres-password
      vault:
        existingSecret:
          # -- should an existing secret be used?
          enabled: true
          # -- name of the secret
          name: vault-unseal-secret
          # -- key to retrieve the secret from
          key: root
      ebsiTest:
        client:
          existingSecret:
            # -- should an existing secret be used?
            enabled: true
            # -- name of the secret
            name: tenant-in2-wallet-sealed-secret
            # -- key to retrieve the secret from
            key: ebsi-client-secret
        userData:
          existingSecret:
            # -- should an existing secret be used?
            enabled: true
            # -- name of the secret
            name: tenant-in2-wallet-sealed-secret
            # -- key to retrieve the secret from
            key: ebsi-user-password

  # Wallet Frontend subchart configuration
  wallet-frontend:
    # -- should be enabled?
    enabled: true
    # Image configuration
    image:
      pullPolicy: Always
      tag: v1.8.0-snapshot
    # Application specific configuration
    app:
      logsEnabled: false
      colors:
        primary: "#00ADD3"
        primaryContrast: "#ffffff"
        secondary: "#50c8ff"
        secondaryContrast: "#50c8ff"

  # Wallet PostgreSQL subchart configuration
  wallet-postgres:
    # -- should be enabled?
    enabled: false

  ## Keycloak subchart configuration
  keycloak-wallet:
    # -- should be enabled?
    enabled: false

  ## Keycloak PostgreSQL subchart configuration
  keycloak-wallet-postgres:
    # -- should be enabled?
    enabled: false

