apiVersion: v2
name: keycloak-bitnami
description: Chart holder for ArgoCD
type: application
version: 0.0.1
appVersion: "v0.0.1"
dependencies:
  - name: keycloak
    condition: keycloak.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 24.3.2
