mysql:
  fullnameOverride: trusted-issuers-list-database
  auth:
    existingSecret: til-database-secret
  initdbScripts:
    create.sql: |
      CREATE DATABASE til;
      CREATE DATABASE ccs;
  image:
    registry: docker.io
    repository: bitnami/mysql
    tag: 8.0.31-debian-11-r10
    pullPolicy: IfNotPresent

