identity-security:
  dome-issuer-keycloak:
    fullnameOverride: keycloak
    nameOverride: keycloak
    image:
      repository: in2workspace/dome-issuer-keycloak
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: v1.0.3
    readinessProbe:
      path: /keycloak/health
    livenessProbe:
      path: /keycloak/health
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
      hosts:
        - host: issuer.dome-marketplace-lcl.org
          paths:
            - path: /keycloak
              pathType: Prefix
      tls:
        - hosts:
            - issuer.dome-marketplace-lcl.org
          secretName: issuer-tls-secret
    # Keycloak Configuration
    keycloak:
      proxy: edge
      logsCertsLevel: TRACE
      logLevel: ALL
      admin:
        username: admin
        password: admin
        existingSecret:
          enabled: false
          name: keycloak-secrets
          passwordKey: keycloakAdminPassword
      relativePath: "/keycloak/"
      hostname:
        url:
          # if deployed locally set to false
          externalService: true
          scheme: https
          # change by the external url or set to localhost if deployed locally
          host: issuer.dome-marketplace-lcl.org
          # internalPort is only used if externalService is false
          internalPort: 30002
          path: /keycloak
        adminUrl:
          # if deployed locally set to false
          externalService: true
          scheme: https
          # change by the external url or set to localhost if deployed locally
          host: issuer.dome-marketplace-lcl.org
          # internalPort is only used if externalService is false
          internalPort: 30002
          path: /keycloak
      https:
        certificateKeyFile: /opt/keycloak/pem/server.key.pem
        certificateFile: /opt/keycloak/pem/server.crt.pem
        trustStoreFile: /opt/keycloak/truststore/truststore.jks
        trustStorePassword: pempas
        existingSecret:
          enabled: false
          name: keycloak-secrets
          trustStorePasswordKey: keycloakTrustStorePassword
        clientAuth: request
      db:
        host: postgres-keycloak
        port: 5432
        externalService: false
        name: postgres_keycloak
        username: postgres
        password: postgres
        existingSecret:
          enabled: false
          name: keycloak-secrets
          passwordKey: keycloakDbPassword
      mail:
        host: smtp.ionos.de
        port: 587
        from: digitalidentitysupport@dome-marketplace.eu
        fromDisplayName: Digital Identity Support Dome
        replyTo: digitalidentitysupport@dome-marketplace.eu
        existingSecret:
          enabled: true
          name: issuer-secret
          userKey: username
          passwordKey: password
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              ssl:
                enable: false

    # Issuer API Configuration
    issuerApi:
      url: http://issuer-api:8080/issuer-api
      externalUrl:
        # if deployed locally set to false
        externalService: true
        scheme: https
        # change by the external url or set to localhost if deployed locally
        host: issuer.dome-marketplace-lcl.org
        # internalPort is only used if externalService is false
        internalPort: 30001
        path: /issuer-api

    # Pre-authorization Configuration
    preAuth:
      lifespan: 10
      lifespanTimeUnit: MINUTES

    # Token Configuration
    token:
      expiration: "2592000"