dome-dss:
  app:
    internalServerPort: 8080

  authServer:
    internalDomain: "http://dome-issuer-keycloak:8080/issuer-keycloak"
    externalDomain: "https://in2-dome-marketplace-test.org/issuer-keycloak"
    realm: CredentialIssuer