apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tenant-in2
  name: vault-check-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    resourceNames: ["vault-server-0"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    resourceNames: ["vault-server-0"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list"]