---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secrets
  namespace: identity-security
spec:
  encryptedData:
    keycloakAdminPassword: AgBc40dh7Qz+uMvsQiwmNI4NPI43/+dcf1MJkLs6s1m/nJVY+uZUBLDByeEVTkMhCCSnCBsmQKsFlVzP8wiZFtd9hPKJvGify1p8HxU5+0AId4+IHUzIFCOGXfeIwizowTvTRKb3blYueLWR/4uQPMoRufPsesnyytHdmcoicMh0KpnAailPOBmK/J7k9p2UKnbIWNZO2JSZK06VT0tft63k8lke/GpPm6t8zMOoyDuWHgRkzL1rU2w6C+ujd7xM9+VjTA29vrqiaXJIcMir42+Ja/9NMC/GbZFj0v/CMlT/1CHpG7Mlzbr8a1fpMvr4/LYrgrfh3jNeC4G9b2lN5pN0Gj3Sf4Ph+8lkaZVqgyFl8S771eY4nFzq/wu4N4BdS73+WTJW1G2JmUxPbfirz9FsTsT6ibpiz2K5KLRF0a4Ht6PoJT8EJkZk7duTuuBHR5VWCAMaqSyjuRJWs3YcUSOqM37gxmLLkL1OIat0a9gJHGeUjZQdlH+v6Tnj7bERldypRGgI+TLIR5kkRBXTfDpR10b6QP4feF/hQF2Aa3HSMRGWRZFWcxwiFPpK9HtP7CfQNI15E1yI5gosYzwR7UF+RdGFcsE5RdAeuhKppKs7TNCznQI7Q6hNv4ZI02Mx2W7NPVDmgZxNB8KabPxXa/MYKUvFduEwdCHx34U+nY0sA6yuwC/GeAg1y5hK3Xee1rEtbF3AZw==
    keycloakDbPassword: AgAq7Ks9dbSV3NttZ1nnaO86jg00wurtA5ykl1/tL2bD4qxRgDluJCe0oDlWFMeHXKXofZonhoaK+qLv07a1itlHIFfHSDaZARw7YepzSkz0NEShatPEzokqueEmaIDLhjFQfGFU6bGGRDx3/rc/PXsAr3QtZWby5NoQvcqtoulgkprDdxTiFLxkxihrhou1vl3kHo4HwUsl2sssMaNhjj4os+Dj1X1FVm6M/y5PWCpjE6x7k250RXGg9JNUTbuW6MGiohcb8jXTzzVAM1iTqnJKNTh7Mwkvp5AUUEtYCFx9bp35Ss3bZo36ES6uOB825ZHASmssP+X/SM9wxPwYIOZKbzOHCx7PGZkKCwtNyIEpRnG3F/Qx+HfuKudq3YQXEKFB7ShHzEcRpV5m7NDeBWWC6ejpl9C6YfPlzQwN19Qpzt0VnW0kAuDW1lDFAZYDjjN7iS8ZqWcy7tKQtLJwdbEC0kvtwwIqtxH7K+Z77MiXra3N0TP/AG9h+bQvYM8vRpUOhNqBELKT1W7tGhETaCBlnyIu86J57bfAv4w9reUqkwUAx3DNKiVMDZsLkP0aeNwRyV6H48X1ZtW1YNg8lZkUT9nBOaulDW7aap62I8fxwAzQlg438Qb4I3+pIqgI1GBQUFq1XLWE744mZ6x6UEIStJI/o+P5Lsf/gH5tpPwIpAixpfS3xn726dZZvqE5yDmHYjcw4qeFQA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secrets
      namespace: identity-security
