---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dome-dss-certificate-secret
  namespace: in2
spec:
  encryptedData:
    password: AgC5RfiZXS4aonQcRENaDkLvl5HY+0PtUmXTAlTyqLUXFbUfOLLC8JMUt04kQSbnMdPRsMZGzqx8AP+ieYvMrDgyl8wqeU8Hgjzbx0Ut8Y5YhP0/rR7yxib+psY0RzKNOod2tqrKrKYNE3iTjuy3AR9LR9EDcxPpD1KrdFoVepYpod0nvKDRfqXF37mnTqMZRH78ZhvqGSKmM9L5/kek1JjTwge6Vhx0DCk8RAaDWAaA6s8GDGunbyIhmbFHiN6MmX2FYFEuf4vHGkf9rVGeFSKpWyS5aJ3ItFxhfyzhRpD6bBRs4C1Ylt1v68hhXmT0rKk1jvGs+1fdo0GM+di1CObJ9KINzH3FdR26jopTv+r65Wf/TxbZeZb9wTAEatKG/mecBuSad1OECoRLDe66JMFJrMbBjBVkePPTDzR/fOl+dCf8YEdr/o617PFFYzrrspT+04dZbC0RAjeiWjQYunXbiq7joQ9IwaOdgVYMKNxwMvn9pir3sdx0xXA+10ifOA5sihGFC1UG2U9Yiggx9PdXobUiQJEFyBEKsjlVlrSZEcbTQ3X1BTpwztmtIb+JFWbYKp/XE7DGyaNRsGi+iGyYY/Txl+maQ2TRQlRKieK2aDM+Ei6stFoMsT1rTYCPjn3ll7fPilknaPqbuIDccgXhcXuuA0yYFzpWYdWv2BUPzHcISEJ5CWpUXN3XBSRltGeEQcB+fbB0tQ==
    token: AgA25fV0IVfBRVIeFySRfcdq2anqnZS5LMF3wRdPsIORBAzy5bJvPUCvU6Q7aQKXQE0OvIXnInigGw6YCTFebWa9KfJPvdzMdpiTax0ehvVh5QLyqj/LnNbA0fXl+1r7TWXoaDlXM20Sj3l5sSQ7tdho1PWrAPXUU9jZKGVj+j5ZtWVE6WEifdXKE0kX0PpGPayxBpqawO466ieHQ5HLZfak2xU/YT7BhpdQffV1PJGwirsx/pD/rMejYppySLezOq7ZDDixPM6czi+VivijR4WhRM0Likg9649cYa2D0rSr8a5Si19Nh4fX3OXsn9QTNtcKyr/fi0LkGQaTUf/Ru9jiLfX3Bxv4SFnu1O9TZw7dTZJuBjBeOCvY19gYSeQKzt9PAYYaYPm+LoLLaa3XxkYkHvjlu8ea4OpP9fY4t+3qOzVxr/ym3eVF4ChuFdhvKDBSxB1zbzWObuBIXhhc5wGVGNyfza5jREVF/WJHj8N4KUonPpNVWrhu1bUA5NlzehJoHBYqAaZ1m5cCNg2vk7IqTS1ZoK+IyrsQSiXIMpYWKbab1dKnCoFSMAXRQYwJ8zyynlXYSTtzO9PHxWqPfUyM+yfJCLTYzqd6f1RskuQ4OXQwXuQqO7jZdABv1nTVIv8KWOZfWISCO4+I7+gSgagsuvja2Zd5bTbqgFf2aTpCjS2S43UB7sXnXgxJoweEqrmtl+e7AcnRapSa38P0yqPiqQfLJMyli/wqu+m0
  template:
    metadata:
      creationTimestamp: null
      name: dome-dss-certificate-secret
      namespace: in2
