apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: argocd
    environment: development
    team: architecture
  annotations:
    argocd.argoproj.io/sync-options: "PruneLast=true"