apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-in2-vault
  namespace: argocd
  labels:
    purpose: in2
spec:
  destination:
    namespace: tenant-in2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/tentant-in2/vault
    repoURL: https://github.com/in2workspace/in2-dome-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true