postgresql:
  global:
    storageClass: ""
    security:
      allowInsecureImages: true

  ## network policy configuration
  networkPolicy:
    enabled: false

  auth:
    username: postgres
    existingSecret: tenant-in2-postgresql-secret
    secretKeys:
      userPasswordKey: postgres-password
    enablePostgresUser: true
    database: in2

  service:
    type: ClusterIP
    ports:
      postgresql: 5432
#    port: 5432

  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 16.0.0-debian-11-r13
    pullPolicy: IfNotPresent