vaultPodName: wallet-vault-server-0
namespace: in2
unsealSecretName: wallet-vault-unseal-secret
vault:
  fullnameOverride: wallet-vault
  injector:
    enabled: false
  server:
    podAnnotations:
      backup.velero.io/backup-volumes: data
    persistence:
      enabled: true
      annotations:
        backup.velero.io/backup-volumes: data
      persistentVolumeClaimRetentionPolicy:
        enabled: true
        whenDeleted: Retain
        whenScaled: Retain