vaultPodName: wallet-vault-server-0
namespace: in2
unsealSecretName: wallet-vault-unseal-secret
vault:
  fullnameOverride: wallet-vault
  injector:
    enabled: false
  server:
    service:
      general:
        annotations:
          backup.velero.io/backup-volumes: data,config,home
      active:
        annotations:
          backup.velero.io/backup-volumes: data,config,home
    podAnnotations:
      backup.velero.io/backup-volumes: data,config,home
    persistence:
      enabled: true
      persistentVolumeClaimRetentionPolicy:
        enabled: true
        whenDeleted: Retain
        whenScaled: Retain