apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-red-mysql
  namespace: argocd
  labels:
    purpose: tenant-red-marketplace
spec:
  project: default
  source:
    repoURL: https://github.com/in2workspace/in2-dome-gitops
    targetRevision: HEAD
    path: charts/tenant-red/marketplace/iam/mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-red-marketplace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true