postgresql:
  commonAnnotations:
    wistefan/rollout-injecting-webhook: ignore
  fullnameOverride: postgresql-keycloak
  auth:
    username: keycloak  
    enablePostgresUser: true
    existingSecret: postgres-keycloak-secret
    secretKeys:
      adminPasswordKey: postgres-root-password
      userPasswordKey: postgres-password
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use
  primary:
    initdb:
      scripts:
        create.sh: |
          psql postgresql://postgres:${POSTGRES_POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak_wallet;"
          psql postgresql://postgres:${POSTGRES_POSTGRES_PASSWORD}@localhost:5432 -c "ALTER DATABASE keycloak_wallet OWNER TO keycloak;"
