dss:
  fullnameOverride: dss
  nameOverride: dss
  app:
    internalServerPort: 8080
    config:
      sourceName: yaml
    certificate:
      existingSecret:
        # -- should an existing secret be used
        enabled: true
        # -- name of the secret
        name: issuer-secret
        # -- key to retrieve the token from
        key: dssPassword
    vault:
      provider: hashicorp
      host: vault-server
      scheme: http
      port: 8200
      existingSecret:
        # -- should an existing secret be used
        enabled: true
        # -- name of the secret
        name: vault-unseal-secret
        # -- key to retrieve the token from
        key: root

  authServer:
    internalDomain: "http://keycloak.identity-security.svc.cluster.local:80"
    externalDomain: "https://keycloak-dev.ssihub.org"
    realm: in2-issuer