---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: desmos-scorpio-db-secret
  namespace: access-node
spec:
  encryptedData:
    password: AgB4zHdDWaOApBi+vGNyKWRcjyrnuK2m7+oFFlADCR2cem0n9gFUnJBLO81cffV5gCFroit7tLe+yjZr37stgeVCjUbK9z3BLi4V0H9snaijUX2WV2QKt4zc+sj96pFgKuummaOIfyDcIRQ0Yw9e8vIOVOXPX3d0ez2OmsZwfwRlPa8idkZggph4s7W7IpqRjMBVSIOZMIxnHUTcIg8bdtIYDMK4bArLIsi/75jzByyInl2+lJBrPfK4C6k5VDofjUCyz18lQsYnNIVMXg7TdDe5DL2hGblywqkCD9qxLMz+BZKEQ4OlxtnGi915/AOe83yyJMXoPUVWRZg8B+v3ou/4lPDAE1U9AKEAzzduOfqbwawnJhZVaHx2IooQXQE4rptLa1tT+kiO2w1hZ6b7Rep+rLFq6ibthqTzOMLoYGq7A9igFrO7BFV8S/ep7vNYqCOmNu81CQHTI//5DzVqaAwkPuQZR/Jr0novOe8QVhXW2zVpRBGkfJmhOvGvT1Iu+pujoRSP0GTgKfcH8u5Qz559TvIN2rHxZT0qP4kaEs69Yd0pxveecQFEHU+Klg2FdZpqhwinDILYV6p8dZIQJzX69f3hw0BQn3E/ONy6JdnxucgAcyVO3pVY/sjFEL9lM7HOQ/8JTnuNZDXg0TwCtAz1cdgzdAu2sDwUiy1sM1N0w9A5BOfeHsgYTWYSYVhRLqVD6w0NIsOzdQ==
  template:
    metadata:
      creationTimestamp: null
      name: desmos-scorpio-db-secret
      namespace: access-node
