postgresql:
  commonAnnotations:
    wistefan/rollout-injecting-webhook: ignore

  fullnameOverride: postgis

  auth:
    # Credentials for scorpio
    username: scorpio
    enablePostgresUser: true
    existingSecret: postgres-secret
    secretKeys:
      adminPasswordKey: postgres-root-password
      userPasswordKey: postgres-password

  # Init DB
  primary:
    initdb:
      scripts:
        enable.sh: |
          psql postgresql://postgres:${POSTGRES_POSTGRES_PASSWORD}@localhost:5432 -c "CREATE EXTENSION postgis;"
          psql postgresql://postgres:${POSTGRES_POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE ngb;"
