apiVersion: v2
name: cert-manager
description: Chart holder for ArgoCD
type: application
version: 0.1.0
appVersion: "v1.12.4"

dependencies:
- name: cert-manager
  version: v1.12.4
  repository: https://charts.jetstack.io
