replicaCount: 1

image:
  repository: quay.io/jetstack/cert-manager-controller
  tag: v1.12.4
  pullPolicy: IfNotPresent

webhook:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/jetstack/cert-manager-webhook
    tag: v1.12.4
    pullPolicy: IfNotPresent

cainjector:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/jetstack/cert-manager-cainjector
    tag: v1.12.4
    pullPolicy: IfNotPresent

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 443

resources: {}
