---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: issuer-api-mail-secret
  namespace: in2
spec:
  encryptedData:
    password: AgA/OV8BU0jSXCM6XVwBm4PYAtUDlK7v8I1CwrFmUWGW+FcnDAdjEAhqWIfA44vvuNmbIdQ8YCWsY18XqNNxZSFFmSN8PhlRogIR4P4IA7aqiAY1P7LkUvLmGa5kkOmQu8Mk4OiBCMGfIopbneqmvjCAWxjVGawUDOtoyXmPY/tW2lTReER22LoGpozfzkP1qI/uegdg9GJQP3BxF55UWuMA6r1AwQaudmOd4rPBp4oYiYebpdmIv1SDSPpSfGIY/q+FjZYuDDkktobAy2+1QeRFSo0fvZ3BgqTJaIR7Ha/bPhZTXVfybeA8N7JC9ejroK6otZ++8/4+RcdguXh9XlnIoFo9HED38qoZvvaxc4e9MRTtJMQmgU0Um5eQ14IaYtUHrisvDBRTmDk6dtlUus/m9YPjrEEP+NT8DIh/yo6R7FNv0w18RcnwBJKdK6D48yfuBh590JJRZleKbqwTmQGlZYg6H92rNFWvvf1QYOfX1FzkUbVi9bOhLFmmFakNkbNPI34soD5hhChfcmKOs2tgWunpgr7U1J8VcoomYdnxpCHNIwOhetPgIrvtgasaBn9LbSJoFW2HDf0te8Dj9dLb194IDoRiKW9K/V7f6P+7+hiuOrqb//JopTXrRGvgDwLRFSXkZPD8UUkHriFckgniI0Nb3rMIZdxrs1szZl9qfGAr/xf+MDG1CmlVUj/dUo2AXNChJdVsMyKESzFDUjRf3Sjw
    username: AgADI5kThlLlAw/AAjoSt4sBwG4xl/yj3g8Kesjv/6oK9lDgTzYFx2qV7x+TJgrnjRejUchbX6jqV1alxUvfIHz1oyQM7HlRQLUaApfHPbRYhXvSEBjtsUdyFg3apusQGCiexq6bY9xaDYcoY5mPSSO6qSvyAXAE5uJi7QZOZETqhQd+MFS/J8F5gcN/XuQx6YjTu/bvYrtU0P54HQ8MjGNhcZabTjM4CX6jlYxJZBn+SPoxjD1rLAhooudVMUHPNj7x+BHE7o0SBYDhbNRXb9wgXND0gvH1Y6ZSbtcqtmIYXvrum/REIGYsYk8JatUc0DXYs6d2lhQKylbcazNi/57XuGmOnql6cb2kKxOn8NufrI4r4pvX8pdIuxVfA7SHOAWOEgsriD7paA2hGY8HMw7yMpjUAkrZ+H+gBsJjJbTb93M4eNMqvIObtSI+5iWxF3UoJZ/wTOCpo9yc6136ZyXrlbt3v+1ap2Ka0hoDi8ihAaf03f5t7+xFGbC0jGBYg8vQ8uOlQxVun9qmKBZggISw/DmPwjGyqxch9rkJErw5CE/AYCEvj5v1cG5DIz8WCtgA4xCIqoWYINMsS/BsiDOBVa64WYO9ZKyCSTXEnv25Ydq3zX5Eo1BuXmnQhtz6YAQV4mVEBB2dljYUphrVX4q7nmZqvz7xGtPimUDK/ZaGBaFJXjCvyskXxmDO6w03OhOWK/Sx32TM91X5AZN4nzaJYNXWNg1cfDdayth0YCFF4SRfn3PcQwYQd1c=
  template:
    metadata:
      creationTimestamp: null
      name: issuer-api-mail-secret
      namespace: in2
