---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: issuer-keycloak-mail-secret
  namespace: in2
spec:
  encryptedData:
    password: AgA920Fz+hda97QAQQdOv6oO0LsWIeDednHizMivHKvrdV24XItmA5Ww55WuC0nHaqS/NiFc0e5g8DsNtWJoZfbqUXbwSwJk/TkF8EmXk4EqNUPuiLMCuJ+TO9Kf1woZmKVtxpyalop4pHSsoJ2V02526oCLwfpjXFYJSOE/Y6oYfULHA5wgojN1gaP8z8UtwVMj0fWlEbUvAg99luEQmHq+uySZ18YWkrkeq2sWSNZtEL9AM3Udi5Tg0bjlC9VGPh8qGOnQVqKmP83OuEXUmWvtZR/txTavTGSGwBfYWGn5oJyWwP1zQpX4XLVqtOZlgIb2w/vLyI/iKMD0G4IGOFt6bevLL3MVtZENGOLX0+AivicmT96rjNrZedKy204C3b4qtoVugLRMlz87RmnuZjr6d6vnXfKsSK/P27flpC3TuuOrPMDMSO/48cAkezjHNNn46XLJEOCbQysS7IVZm7eiBjqwG9c1KmgwhuDYRQTmpZSjRZTS161cAe8bOCLT6MJxSBv4tb6r5+pWG1SBuqbAOu2pBGRAYyzWfBFhF8yTucinv+oqQ82FSCs3+zIIyTQYgyZGK03wJqYmZS4k5WPdk1qI2RXGgY26oCBplAqr0PkYkoE7XqmZuXhEBnmmar2fLSkd3jwClMQGhba+Zo88jBl/ZH2vVK/rnDstcZhZ6SKM98Ar7OWsLIJOVReSFR9CnO/5Ub2rbtQg+IBu+h1jZs9A
    username: AgCOoMGLD122DIN49zgKkWSbZwlzWWFw4fUReXFEVRp6nMG592rYA/boakbtxw1mwWGyYPxldumdnhe0H+8nfWCFBxziq6rYuWPvoVJI/2PaUMbE4JMgakYWW5N0bum2vxz27xLcSTA/F/hn1GMp8OWjBgF/oh9tswQvAF9/aD0OvmYLAeoL1Har3QvDf5ZAdEK+ewaoOsIKcE66wxzLdslMZ2YjxS7/Ubc2YkA4e2bx45J8dFHO2bCf/qYs8Z8nZJfGDgr3jX8PSV2UWLhG4ZHzp44pX9lDQsm9fwvr7noS6S9ka9mAre9t+UY7CUeyZ5nygQc3Nobr1lcoCunT9a8PXy6o7klyspDTnlm2gtfai2GgrkcXrYosB4PqrvZidWMynuDje5JOLtyy+Z9nkin87t3uSEv3RlusDLXsGikhWuYnWxv8lQoUWZA5HmqDKzO1n8vGaRHJoropxHi6Hse3wAguFoggUeZJMd4Vbk8EhuSDPeWRs3A33y2tJcXNkpIJ4EN/7MJ/xk/fGyuYZUIM4FZv5PpkI2z+ADgdajq9UjxAzMhyzoceUhxz8D50rb9EymrUxO7lBj1o592dHbpFkNf/yLxLNlTiGEkOKqVl+IlKlwFqOrzHSGKHfAtqav6SPlb/QDwRhHyAXOup907uMSfl8EgyMW7f9WuvicHFkQnjyPvZCvlJc/1lvyW1MFgSPlMHkuTTY6VBL4ZdwHeZVFwZq57TaWcZ0+rA/aFs1W1llisVPUdzgZE=
  template:
    metadata:
      creationTimestamp: null
      name: issuer-keycloak-mail-secret
      namespace: in2
