keycloak:
  keycloak:
    enabled: true

  postgresql:
    enabled: false

  externalDatabase:
    host: "postgres.ssi-hub.svc.cluster.local"
    port: 5432
    user: "postgres"
    password: "postgres"
    database: "postgres_ssi_hub"