keycloak:

  keycloak:
    enabled: true

  global:
    imageRegistry: "docker.io"
    security:
      allowInsecureImages: true

  image:
    repository: in2workspace/dome-issuer-keycloak
    tag: v1.0.3
    pullPolicy: "IfNotPresent"

  postgresql:
    enabled: false

  externalDatabase:
    host: "postgres.ssi-hub.svc.cluster.local"
    port: 5432
    user: "postgres"
    password: "postgres"
    database: "postgres_ssi_hub"

  extraEnvVars:
    - name: DB_SCHEMA
      value: "keycloak"
    - name: KC_DB_SCHEMA
      value: "keycloak"

  initContainers:
    - name: prepare-write-dirs
      image: docker.io/in2workspace/dome-issuer-keycloak:v1.0.3
      command:
        - /bin/bash
        - -c
        - |
          echo "Creating writable directories in /emptydir"
          mkdir -p /emptydir/app-quarkus-dir /emptydir/app-data-dir /emptydir/app-providers-dir
          echo "Directory creation completed"
      volumeMounts:
        - name: emptydir
          mountPath: /emptydir