keycloak:

  keycloak:
    enabled: true

  global:
    imageRegistry: "docker.io"
    security:
      # Flag to allow the use of images that are not from Bitnami. By default, the use of any image outside the Bitnami ecosystem is disabled.
      allowInsecureImages: true

  image:
    repository: in2workspace/dome-issuer-keycloak
    tag: v1.0.3
    pullPolicy: "IfNotPresent"

  postgresql:
    # Flag to disable the configuration in the chart that creates a PostgreSQL database from the Bitnami umbrella.
    enabled: false

  # Configuration for the external database that the Bitnami Keycloak chart connects to.
  externalDatabase:
    host: "postgres.ssi-hub.svc.cluster.local"
    port: 5432
    user: "postgres"
    password: "postgres"
    database: "postgres_ssi_hub"

  # Flag that disables the initialization scripts from the Bitnami chart.
  enableDefaultInitContainers: false

  # Configuration for container permissions (required for writing dependencies such as Quarkus, etc...).
  containerSecurityContext:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false

  customLivenessProbe:
    httpGet:
      path: /health
      port: http

  customReadinessProbe:
    httpGet:
      path: /health
      port: http

  # Environment variables needed for deploying our custom Keycloak image or other dependencies.
  extraEnvVars:
    - name: KEYCLOAK_ADMIN
      value: "admin"
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: "admin"
    - name: KC_HTTP_RELATIVE_PATH
      value: "/keycloak/"
    - name: KC_HOSTNAME_URL
      value: "http://postgres.ssi-hub.svc.cluster.local:5432/keycloak"
    - name: KC_HOSTNAME_ADMIN_URL
      value: "http://postgres.ssi-hub.svc.cluster.local:5432/keycloak"
    - name: KC_HTTPS_CLIENT_AUTH
      value: "request"
    - name: KC_DB
      value: "postgres"
    - name: KC_DB_USERNAME
      value: "postgres"
    - name: KC_DB_PASSWORD
      value: "postgres"
    - name: KC_DB_URL
      value: "jdbc:postgresql://postgres.ssi-hub.svc.cluster.local:5432/postgres_ssi_hub"
    - name: KC_DB_SCHEMA
      value: "keycloak"
    - name: DB_SCHEMA
      value: "keycloak"
    - name: ISSUER_API_URL
      value: "http://issuer-api:8080/issuer-api"
    - name: ISSUER_API_EXTERNAL_URL
      value: "https://issuer.dome-marketplace-lcl.org/issuer-api"
    - name: PRE_AUTH_LIFESPAN
      value: "10"
    - name: PRE_AUTH_LIFESPAN_TIME_UNIT
      value: "MINUTES"
    - name: TOKEN_EXPIRATION
      value: "2592000"