keycloak:
  enabled: true
  args:
    extraEnvVars:
      - name: KC_DB_URL
        value: "jdbc:postgresql://postgres:5432/postgres_ssi_hub"
      - name: KC_DB_USERNAME
        value: "postgres"
      - name: KC_DB_PASSWORD
        value: "postgres"
      - name: KC_DB_SCHEMA
        value: "keycloak"
      - name: DB_SCHEMA
        value: "keycloak"

externalDatabase:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "postgres_ssi_hub"

postgresql:
  enabled: false