keycloak:

  keycloak:
    enabled: true

  global:
    imageRegistry: "docker.io"
    security:
      allowInsecureImages: true

  image:
    repository: in2workspace/dome-issuer-keycloak
    tag: v1.0.3
    pullPolicy: "IfNotPresent"

  postgresql:
    enabled: false

  externalDatabase:
    host: "postgres.ssi-hub.svc.cluster.local"
    port: 5432
    user: "postgres"
    password: "postgres"
    database: "postgres_ssi_hub"

  extraEnvVars:
    - name: DB_SCHEMA
      value: "keycloak"
    - name: KC_DB_SCHEMA
      value: "keycloak"
    - name: QUARKUS_TEMP_DIR
      value: "/tmp"

  enableDefaultInitContainers: false

  containerSecurityContext:
    readOnlyRootFilesystem: false