apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  labels:
    purpose: marketplace
spec:
  project: default
  source:
    repoURL: https://github.com/in2workspace/in2-dome-gitops
    targetRevision: HEAD
    path: charts/tenant-dome-2/marketplace/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-dome-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true