apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: in2
  name: vault-check-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "update"]
