apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: in2
  name: vault-check-role
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list"]
