dome-dss:
  app:
    internalServerPort: 8050
    config:
      sourceName: yaml
    certificate:
      existingSecret:
        # -- should an existing secret be used
        enabled: true
        # -- name of the secret
        name: issuer-secret
        # -- key to retrieve the token from
        key: domeDssPassword
    vault:
      provider: hashicorp
      host: dome-dss-vault-server
      scheme: http
      port: 8200
      existingSecret:
        # -- should an existing secret be used
        enabled: true
        # -- name of the secret
        name: dome-dss-vault-unseal-secret
        # -- key to retrieve the token from
        key: root
      global:
        security:
          allowInsecureImages: true
      image:
        registry: docker.io
        repository: bitnamilegacy/vault
        tag: 1.16.3-debian-12-r1
        pullPolicy: IfNotPresent

  authServer:
    internalDomain: "http://dome-issuer-keycloak:8080/issuer-keycloak"
    externalDomain: "https://issuer.dome-marketplace-lcl.org/issuer-keycloak"
    realm: issuer-dome