dome-dss:
  image:
    repository: in2workspace/remote-signature-ms
    # Overrides the image tag whose default is the chart appVersion.
    tag: v0.6.0
    pullPolicy: Always
  app:
    internalServerPort: 8050
    config:
      sourceName: yaml
    certificate:
      existingSecret:
        # -- should an existing secret be used
        enabled: true
        # -- name of the secret
        name: dome-dss-certificate-secret
        # -- key to retrieve the token from
        key: password
    vault:
      provider: hashicorp
      host: dome-dss-vault-server
      scheme: http
      port: 8200
      token: hvs.WQlzYBJKEUq8S9jbNnm5ZzMW
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: dome-dss-token-secret
        # -- key to retrieve the token from
        key: token

  authServer:
    internalDomain: "http://dome-issuer-keycloak:8080/issuer-keycloak"
    externalDomain: "https://in2-dome-marketplace-test.org/issuer-keycloak"
    realm: CredentialIssuer