dome-verifier:
  image:
    repository: in2workspace/eudistack-verifier-api
    tag: v2.0.0
    pullPolicy: Always

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
    hosts:
      - host: verifier.dome-marketplace-lcl.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - verifier.dome-marketplace-lcl.org
        secretName: verifier-tls-sec

  app:
    frontend:
      urls:
        # Placeholder for onboarding URL (REQUIRED)
        onboarding: "https://knowledgebase.dome-marketplace.org/shelves/company-onboarding-process"
        # Placeholder for support URL (REQUIRED)
        support: "https://ticketing.dome-marketplace.org"
        # Placeholder for wallet URL (REQUIRED)
        wallet: "https://wallet.dome-marketplace-lcl.org"
      colors:
        primary: "#2D58A7"
        # Defines contrasting text color for primary color (OPTIONAL with default value)
        primaryContrast: "#ffffff"
        # Defines secondary color for the frontend (OPTIONAL with default value)
        secondary: "#14274A"
        # Defines contrasting text color for secondary color (OPTIONAL with default value)
        secondaryContrast: "#00ADD3"
      # Placeholder for logo source path (REQUIRED)
      # This routes must point to internal folder: src/main/resources/static/img/<file_name.png>
      logoSrc: "dome_logo_white.svg"
      # Placeholder for favicon source path (OPTIONAL)
      # This routes must point to internal folder: src/main/resources/static/img/<file_name.png>
      faviconSrc: "dome_logo_favicon.png"
    backend:
      logging:
        level:
          # Sets logging level for Spring Security
          org.springframework.security: DEBUG
          # Sets logging level for web filters
          org.springframework.web.filter: DEBUG
          # Sets logging level for the custom package "es.in2.vcverifier"
          es.in2.vcverifier: TRACE
      # Placeholder for backend URL (REQUIRED)
      url: "https://verifier.dome-marketplace-lcl.org"
      security:
        serviceIdentity:
          # Placeholder for private key used in identity verification (REQUIRED)
          existingSecret:
            enabled: true
            name: verifier-secret
            privateKey: private-key
            verifiableCredential: verifiable-credential
          # Placeholder for DID Key (REQUIRED)
          didKey: "did:key:zDnaekiwkWcXnHaW6au3BpmfWfrtVTJZrA3EHgLvcbm6EZnup"
      trustFrameworks:
        # Placeholder for the name of a trust framework (REQUIRED)
        - name: DOME
          # Placeholder for trusted issuers list URL
          trustedIssuersListUrl: "http://trusted-issuers-list.marketplace.svc.cluster.local:8080/v4/issuers/"
          # Placeholder for trusted services list URL
          trustedServicesListUrl: "https://raw.githubusercontent.com/in2workspace/in2-dome-gitops/refs/heads/main/trust-framework/trusted_services_list.yaml"
          # Placeholder for revoked credentials list URL
          revokedCredentialListUrl: "https://raw.githubusercontent.com/in2workspace/in2-dome-gitops/refs/heads/main/trust-framework/revoked_credential_list.yaml"