verifier-api:
  image:
    repository: in2workspace/in2-verifier-api
    tag: v1.0.12-snapshot
    pullPolicy: Always

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
    hosts:
      - host: verifier.dome-marketplace-lcl.org
        paths:
            - path: /
              pathType: Prefix
    tls:
      - hosts:
          - verifier.dome-marketplace-lcl.org
        secretName: verifier-tls-sec

  app:
    profile: local
    logLevel:
        app: DEBUG
    externalDomain: "https://verifier.dome-marketplace-lcl.org"
    accessToken:
      expirationUnitTime: DAYS
      expirationTime: 1
    idToken:
        expirationUnitTime: MINUTES
        expirationTime: 5
    loginQrCode:
      expirationUnitTime: MINUTES
      expirationTime: 3
    clientsRepository:
      uri: "https://raw.githubusercontent.com/in2workspace/in2-dome-gitops/refs/heads/main/trust-framework/trusted_services_list.yaml"
    trustedIssuerList:
      uri: "http://trusted-issuers-list.marketplace.svc.cluster.local:8080/v4/issuers/"
    revocationList:
      uri: "https://raw.githubusercontent.com/in2workspace/in2-dome-gitops/refs/heads/main/trust-framework/revoked_credential_list.yaml"
    privateKey:
      existingSecret:
        enabled: true
        name: private-key-secret
        key: private-key
    verifierUiLoginUris:
      onboardingUri: "https://knowledgebase.dome-marketplace.org/shelves/company-onboarding-process"
      supportUri: "https://ticketing.dome-marketplace.org"
      walletUri: "https://wallet.dome-marketplace-lcl.org"