verifier-api:
  image:
    repository: in2workspace/in2-verifier-api
    tag: v1.0.0-snapshot
    pullPolicy: Always

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
    hosts:
      - host: verifier.dome-marketplace-lcl.org
        paths:
            - path: /
              pathType: Prefix
    tls:
      - hosts:
          - verifier.dome-marketplace-lcl.org
        secretName: verifier-tls-sec

  app:
    profile: local
    externalDomain: "https://verifier.dome-marketplace-lcl.org"
    accessToken:
      expirationUnitTime: DAYS
      expirationTime: 1
    clientsRepository:
      uri: "https://raw.githubusercontent.com/DOME-Marketplace/dome-services-directory/refs/heads/main/trusted-service-list-"
    trustedIssuerList:
      uri: "http://trusted-issuers-list.marketplace.svc.cluster.local:8080/v4/issuers/"
    privateKey:
      existingSecret:
        enabled: true
        name: private-key-secret
        key: private-key
    verifierUiLoginUris:
      onboardingUri: "https://knowledgebase.dome-marketplace.org/shelves/company-onboarding-process"
      supportUri: "https://ticketing.dome-marketplace.org"
      walletUri: "https://wallet.dome-marketplace-lcl.org"