apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wallet-api
  name: wallet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: wallet-api
      app.kubernetes.io/name: wallet-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wallet-api
        app.kubernetes.io/name: wallet-api
    spec:
      containers:
      - image: in2workspace/wallet-api:v1.2.0-SNAPSHOT
        imagePullPolicy: Always
        name: wallet-api
        env:
        # Logging Configuration
        - name: LOGGING_LEVEL_ES_IN2_WALLET_SERVER
          value: "DEBUG"
        - name: OPENAPI_SERVER_URL
          value: "https://dome-wallet.eu/wallet-server"
        - name: OPENAPI_SERVER_DESCRIPTION
          value: "Wallet Server"
        # CORS
        - name: WALLET_WDA_URLS_SCHEME
          value: "https"
        - name: WALLET_WDA_URLS_DOMAIN
          value: "dome-wallet.eu"
        # RETROCOMPATIBILITY
        - name: AUTH_SERVER_DOMAIN
          value: "https://issuerkeycloak.demo.in2.es/realms/EAAProvider"
        - name: AUTH_SERVER_TOKEN_ENDPOINT
          value: "https://issuerkeycloak.demo.in2.es/realms/EAAProvider/verifiable-credential/did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa/token"
        # IDP
        - name: EBSI_TEST_URL
          value: "https://dome-wallet.eu/keycloak/realms/wallet/protocol/openid-connect/token"
        - name: EBSI_TEST_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: wallet-server-secret
              key: EBSI_TEST_CLIENT_SECRET
        - name: EBSI_TEST_CLIENT_ID
          value: "user-registry-client"
        - name: EBSI_TEST_USERNAME
          value: "user"
        - name: EBSI_TEST_PASSWORD
          value: "user"
        # BROKER
        - name: BROKER_PROVIDER
          value: "scorpio"
        - name: BROKER_EXTERNAL_URL_DOMAIN
          value: "scorpio"
        - name: BROKER_EXTERNAL_URL_PORT
          value: "1026"
        - name: BROKER_INTERNAL_URL_DOMAIN
          value: "scorpio"
        - name: BROKER_INTERNAL_URL_PORT
          value: "1026"
        - name: BROKER_PATHS_ENTITIES
          value: "/ngsi-ld/v1/entities"
        # VAULT
        - name: VAULT_PROVIDER_NAME
          value: "hashicorp"
        - name: HASHICORP_VAULT_HOST
          value: "vault-wallet-api"
        - name: HASHICORP_VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: wallet-server-secret
              key: HASHICORP_VAULT_TOKEN
        - name: HASHICORP_VAULT_SCHEME
          value: "http"
        - name: HASHICORP_VAULT_PORT
          value: "8200"
        - name: "LOGGING_LEVEL_ORG_SPRINGFRAMEWORK"
          value: "DEBUG"
        - name: "SPRING_WEBFLUX_BASEPATH"
          value: "/wallet-api"
