vaultPodName: vault-server-0
namespace: tenant-in2
unsealSecretName: vault-unseal-secret
vault:
  fullnameOverride: vault
  nameOverride: vault
  injector:
    enabled: false
  # todo try without this
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/vault
    tag: docker.io/bitnami/vault:1.18.1-debian-12-r1
    pullPolicy: IfNotPresent