---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: marketplace
spec:
  encryptedData:
    mongodb-root-password: AgB9ozCXhBiIfc1OmiMeD9BqSzQ3L3thaZdVzofWIpP5eTTuGYZ6j2nv+W7a9Uwn2m0Rv8RWFMTGS88b4jCKCCynQmouxfITs4UbZzbJ3pBSjBvGTGSketEaInLowIE+pF+LK3yN0J6/szsb2LeU+uo7jLSICzxXdsb5/BMOKiFgwA7WK7lCXz76vBqo7zYg+Ui1pSKbc7rxhwjrk/Wag6pDMkWHglw3Y/zHlex/cs06tNlQX9HKUCA83tav9TKC8sa88zYnnvxqlizbor+GWECoUJLd3ThhDioDtI7b2kWjtKX31cD0PjUrwQ031twPTJhb6lf/7ar3mX/LHMvrbAE3Bp/NDjXFBHRehCBMRVywALvtK7IX/qhDfkQFJOKyN4+860aeC2x6XvhOXbZ++Sn4WUD2gQXgA6kVCTmkrq1t7ltDcgiL61x+EpPZ9hjX//hqAonDBmNbcp1U8nJalHBGG0yddRGEJy/eG182AHiHMA5DaM3NsoKGsyGzE6jezBRlJ90+pp3jvSTxKuoHjujA1MXwA9qHP+M1Uws1TuBB29GZfcywaJAMXQtnYV9wDLGS5PvX/mohWKnKL4jKLoL92y+yKm7s9y+Z4q0dKI5xTph9VtAKKbaFZpKBnEAWT4oJ1xVOnUPdHcWXo87hjhHe2vEDHMlteKJhwAgmHX2Mmhpt0WDjYOJQX0nJhWLkKL3dCBe4GwIw6uxlyoI=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: marketplace
