apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: access-node-2
  namespace: argocd
  labels:
    purpose: marketplace
spec:
  project: default
  source:
    repoURL: https://github.com/in2workspace/in2-dome-gitops
    targetRevision: HEAD
    path: ionos/marketplace-2/access-node
  destination:
    server: https://kubernetes.default.svc
    namespace: marketplace-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true