---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-env-secret
  namespace: marketplace-2
spec:
  encryptedData:
    MONGO_BAE_BELP_PW: AgBR1+SlVI7ZCCHlxNJtx01Z2VhmHboXWNC96rX0A5HMzLcWt3JzKdGc2JRXVRywhIMfMkjNH5f9Bko6R/QtySN2CPV0J+k480H4UxQFPBYp+LaBZlYyV6Qo7eYox09V+PCagpGYLOI/we6TX71fWJm5obeJfcfggmwKAAKWrlTk6391dmV0JXKSUsXsSbVluIrkyvVem7NNeO0PIYdTBnjiIWcg5E4KfOcnKutrf9+Iid+1BNam8JVmdU6PTHmZYwWJ/iZIl2keeHpLbOAKECJyUgk3SuFniVD7DcrVoAafZ4CShWswjc+1ftluJQ48S9mPfDyV94Dzrrfk6P9jhSIUkJ2g4Opw2tGpdzE4FnRfAERmUzi8ba1X9Noc0NU2IEld25Ze0Hy+7UdRgpZ/tvG/sM2hAx4Q8olp5lSVxfA3t5ZbJkwyjfMirPsb+fbW56okFpSH3Alyxk5hpCK/cEWk9jHBSmn05MwjcDo6wkDvdCpX73Y9lg5hTN3x1LcK6PD6mW03MNIeabWx0P3279Oq+6yFyLbiQUieD5b7LMaZTu+gl9bufVY85BLz/e+W2Sas4p5JdqtPg9O3s5y55+Qo7utlXJ7GZ1PRiRZFAVWGntH1UYcXg7zArYMKXOD9q55bdyarcKOKAYITc89PIzzOknDZLxfp+apYhzqJlWZX9EnYBQNpaRktqo6udqzoNzgVuujri0Y1z+13Va8=
    MONGO_BAE_CHARGING_PW: AgB0/LC9pn0DN9/NaeUB6d29wzQbrYOBsnz4HrIR40M8ZbNhk7vpha4SJFzbG2vLICZCQqMRDB+tY547fCcJhHNuWX1WD/FAvggaTooVkootC49nlXznWMuNV5FnhP+0QWyME3mB2hEGGzL1e84zweAXm5+IIxmDjvhxHO1e2q8rgKF+4ye8KM8Pc8WUGop8dysvE19bor2W1XfI0zA/cmG9iF1Rp7cNBtgDsabAxcg+5iEoU6hqwWuoeBEWUw/WigcC/OCMXpZvNJWe4B/CjX4BU3+TlYpIYNvfwUjMQaVXAcSv6tW+r5yC0N5RqWoBfZHirVGrMjsZ/wLzjQ97kCgX5gDVGLvdQQqmp3v0I11JHU2s9chj0VXGl00JDOtbKn1kxIuLuJvwPqgUUMTVCiNzvR8PoowMYQis21/HwGObYwbryNvAlZcbOFgmoAvedJ7z98UBUtKp2xkjeF2n5cmOWb5ia+jsGtCRCb8HCvSK0EytjNyfWsflPsvxea4cnvXt+Mf/2vA95/isoIv5ICZaPvufAZc3ylStnvFvNCKhJsVjqDhIUs/VIAsoKFVab/3dkMW5su86Z/AjdlWmbv9wnjF7alAXZ0BplgGvsMs6wlgJkUKMa7K8xzii0SRGpC40Gc/xAHHVIsdTqRLUYiSfX0SQMDWIo+fqlZmfIUAfEOleD6OErrMpIp2OHkZyFPSjV3diBX+r1bfirgY=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-env-secret
      namespace: marketplace-2
