apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    app: {{ include "database.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
  selector:
    app: {{ include "database.name" . }}
