apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  labels:
    purpose: core
spec:
  destination:
    server: https://kubernetes.default.svc
  project: ssi-hub
  source:
    path: charts/namespaces
    repoURL: https://github.com/in2workspace/in2-dome-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true