---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wallet-keycloak-mail-secret
  namespace: in2
spec:
  encryptedData:
    password: AgAfQmyDygClw5oTlrPzoPxeSlasg90y9DaHRv5jv16Tf2EdE1hEyjj99oJVWpDlIGAghGriCQz+Aqj5+CyLXOYW8UiMm1ovBYDX9nez1fzGDsi3/QLZhXfUyy6UUgldHPGJvPoxArkTDrfYuCxKJJvhha02jLcTsMMy1Qe3ZdIthJqqCi/0bVezRFpM76XMf37sNoDFKmCzdV6h4Z/fzHjsmWY3uzSfYY0N/7CgjKO2TMxWJt2C68SKXg+k6UASuDeNG11urkFuHVd7zUBaZSxJenj3i4lwTINjyUheRh5ZJzJRS+8Sx7RXQw0+ecP102wb8OEj/FeOfPAwtxV+n+aP+jUcA4HCU4l9WT4HeRNd/v31HNuk9KQUFu1NlwG1h5uuBQZur+iUpeG4OVIZPocm4TgGWgeZ1MfMPbrrfg4soG/hGyiFnVrUjH+sgt+xK1WN7oaEx/MFehA2p7BFimEdAfEesbHa/viYx/hYkpRfb2/5b9zod5VHAjx2TB7seXbgKCyjwwJ5MYDWnwo2SEJARXXZfiyxIM7yT90Sv8x9zoIVB+JwrsDQRlJrUOKMRg2vrtl8BHylqn1W5VKPVV1VSDsOHwhHMT8+B1lLgme3ZaYAvpK1Sv/+751y9cvyz5a8JROGpqn5Z5zS/8Mfksl5mcX3cNCe18hux7btIdpWeyyoBZSobXe4KE+roDBnC/Bk9AbHfcRLdp+tLLWkFt0Wyjd3
    username: AgCKt1RsfARAGsWWAoeGi9W8L13JDQ8ksTDo1mOEmrmZoTZBVNRDMaz6qBwfXFTNj408uBC3+lVXjx1ePgMtlP6/ld0hzaZgwyx+ZClNt9ddqdLlBBTohlgAPD08PDrIibQ4+i7vt1YfXdaD4joxAulWIcrFo4c57gXHNHX7QZ+kfLXNq1UOUApUGXk/kPxNDdvmwwC70nrbQhmkGnTX7LEn92hHcS+dcfMNz9tabxaZWFjB5lu/d+UdTan/d76NsrZyLj6wKg9dE9JAv7nlX/565MR2bo+QpAVdatmzh7n456GZso5zj2ADLkku07Ekqkc0OOlXQ+sZutvxJYYfE8+eFDAtkWcwCDWxvaLJy5sYdlpgpfHP4byoW9ixZC2iUjoPAkNv5whwGIBw6+eN0HbCzElQl8gbpMwllJcAVvcx1duxE38tW6h/8Rd9N0XfuYzT6obfe/j7Wqp0eHYaVT+F6VC/U2LlkHn8AkTQ6hos62E0F7cmjoxpxSYJt7AtT3lgiShx29VqzjRMb2UyiP7otNrHX3LjBp6FY+26PDq8dzXaC/7odIgRn8VqPstoOL7O69ZQDrfNp8AponFIZYozYTaEbIiJ1hJUKB7SVb3+YS8gkeG9oPaBGmf6kqlZ3AB6ZZsfgl9jj/JoeeoO9Zbz9f/Z/m+ZzUZMvI8n7cl0XEjObpgYjdT9OOwP9YXoZrwVEnNLdfmxfr2VVrHKivDziFxYazega6x3ims+4vSO9uc6xkyd9hb9fwo=
  template:
    metadata:
      creationTimestamp: null
      name: wallet-keycloak-mail-secret
      namespace: in2
