issuer:
  issuer-api:
    fullnameOverride: issuer-api
    nameOverride: issuer-api
    image:
      repository: in2workspace/in2-issuer-api
      # Overrides the image tag whose default is the chart appVersion.
      tag: v1.1.1-snapshot
      pullPolicy: Always
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
      hosts:
        - host: issuer.dome-marketplace-lcl.org
          paths:
            - path: /issuer-api
              pathType: Prefix
      tls:
        - hosts:
            - issuer.dome-marketplace-lcl.org
          secretName: issuer-tls-secret
    ingressWellKnown:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
        nginx.ingress.kubernetes.io/rewrite-target: /issuer-keycloak/realms/CredentialIssuer/verifiable-credential/did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa/.well-known/openid-configuration
      hosts:
        - host: issuer.dome-marketplace-lcl.org
          paths:
            - path: /issuer-api/.well-known/openid-configuration
              pathType: Prefix
              serviceName: dome-issuer-keycloak
              servicePort: 8080

      tls:
        - hosts:
            - issuer.dome-marketplace-lcl.org
          secretName: issuer-tls-secret
    ingressToken:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
        nginx.ingress.kubernetes.io/rewrite-target: /issuer-keycloak/realms/CredentialIssuer/verifiable-credential/did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa/token
      hosts:
        - host: issuer.dome-marketplace-lcl.org
          paths:
            - path: /issuer-api/token
              pathType: Prefix
              serviceName: dome-issuer-keycloak
              servicePort: 8080
      tls:
        - hosts:
            - issuer.dome-marketplace-lcl.org
          secretName: issuer-tls-secret
    app:
      profile: default
      logLevel: INFO
      internalServerPort: 8080
      mail:
        host: smtp.ionos.de
        port: 587
        existingSecret:
          enabled: true
          name: issuer-secret
          mailUsernameKey: username
          mailPasswordKey: password
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              ssl:
                trust: smtp.ionos.de
      remoteSignature:
        externalDomain:
          # if deployed locally set to false
          externalService: true
          scheme: http
          # change by the external url or set to localhost if deployed locally
          host: dome-dss:8080
          # internalPort is only used if externalService is false
          internalPort: 30003
        internalDomain: http://dome-dss:8080
      api:
        externalDomain:
          # if deployed locally set to false
          externalService: true
          scheme: https
          # change by the external url or set to localhost if deployed locally
          host: issuer.dome-marketplace-lcl.org
          # internalPort is only used if externalService is false
          internalPort: 30001
          path: /issuer-api
        internalDomain: http://issuer-api:8080
        configSource: yaml
        cacheLifetimeCredentialOffer: 10
        cacheLifetimeVerifiableCredential: 10
      authServer:
        provider: keycloak
        externalDomain:
          # if deployed locally set to false
          externalService: true
          scheme: https
          # change by the external url or set to localhost if deployed locally
          host: issuer.dome-marketplace-lcl.org
          # internalPort is only used if externalService is false
          internalPort: 30002
          path: /issuer-keycloak
        internalDomain: http://dome-issuer-keycloak:8080/issuer-keycloak
        realm: CredentialIssuer
        client:
          clientId: oidc4vci-wallet-client
          clientSecret: oidc4vci-wallet-client-secret
          username: user
          password: user
          existingSecret:
            enabled: false
            name: auth-secret
            clientSecretKey: authServerClientSecret
            clientPasswordKey: authServerClientPassword
        paths:
          tokenPath: /realms/CredentialIssuer/protocol/openid-connect/token
      ui:
        externalDomain:
          # if deployed locally set to false
          externalService: true
          scheme: https
          # change by the external url or set to localhost if deployed locally
          host: issuer.dome-marketplace-lcl.org
          # internalPort is only used if externalService is false
          internalPort: 30000
          path: /
        internalDomain: http://dome-wallet-ui:8080
      wallet:
        url: https://wallet.dome-marketplace-lcl.org/
      trustFramework:
        url: "http://trusted-issuers-list.marketplace.svc.cluster.local:8080"
      defaultSigner:
        commonName: DOME DIGITAL IDENTITY
        country: ES
        email: domesupport@in2.es
        organizationIdentifier: VATEU-B99999999
        organization: IN2
        serialNumber: IDCES-56565656P
      verifier:
        verifierDidKey: did:key:zDnaekiwkWcXnHaW6au3BpmfWfrtVTJZrA3EHgLvcbm6EZnup
        externalDomain: https://verifier.dome-marketplace-lcl.org
        credentialSubjectKey: did:key:zDnaezLhSFWRZ1zrYQRwLxV8nDWmb2REHoUf7N3qvna1TFina
        existingSecret:
          enabled: true
          name: issuer-secret
          vcKey: vc
          cryptoPrivateKey: private-key
        clientAssertion:
          token:
            cronUnit: MINUTES
            expiration: 2
    db:
      host: issuer-postgres
      port: 5432
      externalService: false
      name: issuer
      username: postgres
      password: postgres
      existingSecret:
        enabled: false
        name: db-secret
        key: db-password

  issuer-ui:
    fullnameOverride: issuer-ui
    nameOverride: issuer-ui
    image:
      repository: in2workspace/in2-issuer-ui
      # Overrides the image tag whose default is the chart appVersion.
      tag: v1.1.0-snapshot
      pullPolicy: Always
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
      hosts:
        - host: issuer.dome-marketplace-lcl.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - issuer.dome-marketplace-lcl.org
          secretName: issuer-tls-secret
    app:
      internalServerPort: 8080
      loginUrl:
        # if deployed locally set to false
        externalService: true
        scheme: https
        # change by the external url or set to localhost if deployed locally
        host: issuer.dome-marketplace-lcl.org
        # internalPort is only used if externalService is false
        internalPort: 30002
        path: /issuer-keycloak/realms/CredentialIssuer
      clientId: account-console
      scope: openid profile email offline_access
      grantType: code
      baseUrl:
        # if deployed locally set to false
        externalService: true
        scheme: https
        # change by the external url or set to localhost if deployed locally
        host: issuer.dome-marketplace-lcl.org
        # internalPort is only used if externalService is false
        internalPort: 30001
        path: /issuer-api
      walletUrl:
        # if deployed locally set to false
        externalService: true
        scheme: https
        # change by the external url or set to localhost if deployed locally
        host: wallet.dome-marketplace-lcl.org
        # internalPort is only used if externalService is false
        internalPort: 30003
        path: /
      knowledgebaseUrl:
        # if deployed locally set to false
        externalService: true
        scheme: https
        # change by the external url or set to localhost if deployed locally
        host: knowledgebase.dome-marketplace-sbx.org
        path: /
      procedures: /api/v1/procedures
      saveCredential: /api/v1/credentials?type=LEARCredentialEmployee
      credentialOfferUrl: /api/v1/credential-offer
      notification: /api/v1/notifications

  dome-issuer-keycloak:
    fullnameOverride: dome-issuer-keycloak
    nameOverride: dome-issuer-keycloak
    image:
      repository: in2workspace/dome-issuer-keycloak
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: v1.0.0-LCL
    readinessProbe:
      path: /issuer-keycloak/health
    livenessProbe:
      path: /issuer-keycloak/health
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
      hosts:
        - host: issuer.dome-marketplace-lcl.org
          paths:
            - path: /issuer-keycloak
              pathType: Prefix
      tls:
        - hosts:
            - issuer.dome-marketplace-lcl.org
          secretName: issuer-tls-secret
    # Keycloak Configuration
    keycloak:
      proxy: edge
      logsCertsLevel: TRACE
      logLevel: ALL
      admin:
        username: admin
        password: admin
        existingSecret:
          enabled: false
          name: keycloak-secrets
          passwordKey: keycloakAdminPassword
      relativePath: "/issuer-keycloak/"
      hostname:
        url:
          # if deployed locally set to false
          externalService: true
          scheme: https
          # change by the external url or set to localhost if deployed locally
          host: issuer.dome-marketplace-lcl.org
          # internalPort is only used if externalService is false
          internalPort: 30002
          path: /issuer-keycloak
        adminUrl:
          # if deployed locally set to false
          externalService: true
          scheme: https
          # change by the external url or set to localhost if deployed locally
          host: issuer.dome-marketplace-lcl.org
          # internalPort is only used if externalService is false
          internalPort: 30002
          path: /issuer-keycloak
      https:
        certificateKeyFile: /opt/keycloak/pem/server.key.pem
        certificateFile: /opt/keycloak/pem/server.crt.pem
        trustStoreFile: /opt/keycloak/truststore/truststore.jks
        trustStorePassword: pempas
        existingSecret:
          enabled: false
          name: keycloak-secrets
          trustStorePasswordKey: keycloakTrustStorePassword
        clientAuth: request
      db:
        host: dome-issuer-keycloak-postgres
        port: 5432
        externalService: false
        name: cred
        username: postgres
        password: postgres
        existingSecret:
          enabled: false
          name: keycloak-secrets
          passwordKey: keycloakDbPassword
      mail:
        host: smtp.ionos.de
        port: 587
        from: digitalidentitysupport@dome-marketplace.eu
        fromDisplayName: Digital Identity Support Dome
        replyTo: digitalidentitysupport@dome-marketplace.eu
        existingSecret:
          enabled: true
          name: issuer-secret
          mailUsernameKey: username
          mailPasswordKey: password
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              ssl:
                enable: false

    # Issuer API Configuration
    issuerApi:
      url: http://issuer-api:8080/issuer-api
      externalUrl:
        # if deployed locally set to false
        externalService: true
        scheme: https
        # change by the external url or set to localhost if deployed locally
        host: issuer.dome-marketplace-lcl.org
        # internalPort is only used if externalService is false
        internalPort: 30001
        path: /issuer-api

    # Pre-authorization Configuration
    preAuth:
      lifespan: 10
      lifespanTimeUnit: MINUTES

    # Transaction Code Configuration
    txCode:
      size: 4
      description: Enter the PIN code

    # Token Configuration
    token:
      expiration: "2592000"

  issuer-postgres:
    # -- should the postgresql deployment be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: issuer-postgres
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    nameOverride: issuer-postgres
    ## auth configuration for the database
    auth:
      # -- username to be used
      username: postgres
      # -- should the default postgres user be enabled
      enablePostgresUser: true
      # -- password to be used
      password: postgres
    ## configuration of the postgres primary replica
    primary:
      ## provide db initialization
      initdb:
        ## provide scripts for initialization
        scripts:
          # -- create the database
          create.sh: |
            psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE issuer;"


  issuer-keycloak-postgres:
    # -- should the postgresql deployment be enabled
    enabled: true
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    fullnameOverride: dome-issuer-keycloak-postgres
    # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
    nameOverride: dome-issuer-keycloak-postgres
    ## auth configuration for the database
    auth:
      # -- username to be used
      username: postgres
      # -- should the default postgres user be enabled
      enablePostgresUser: true
      # -- password to be used
      password: postgres
    ## configuration of the postgres primary replica
    primary:
      ## provide db initialization
      initdb:
        ## provide scripts for initialization
        scripts:
          # -- create the database
          create.sh: |
            psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE cred;"