apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    purpose: in2
spec:
  project: default
  source:
    repoURL: https://github.com/in2wokspace/in2-dome-gitops
    targetRevision: HEAD
    path: ionos/wallet/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: in2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
