apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-dome-issuer
  namespace: argocd
  labels:
    purpose: tenant-dome
spec:
  project: default
  source:
    repoURL: https://github.com/in2workspace/in2-dome-gitops
    targetRevision: HEAD
    path: charts/tenant-dome/issuer
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-dome
  syncPolicy:
    automated:
      prune: true
      selfHeal: true