apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
  namespace: tenant-dome
spec:
  type: ExternalName
  externalName: keycloak.identity-security.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
