---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adapter-secret
  namespace: tenant-red-identity
spec:
  encryptedData:
  template:
    metadata:
      name: adapter-secret
      namespace: tenant-red-identity
